package fr.univtln.bruno.samples.jpa;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Version;
import lombok.*;

/**
 * The Customer class represents a customer entity in the database.
 * It uses JPA annotations to map the class to a database table.
 */
@Entity
@NoArgsConstructor
@Getter
@RequiredArgsConstructor(staticName = "of")
@ToString
public class Customer {

    /**
     * The id field is the primary key of the Customer table.
     * It is automatically generated by JPA.
     */
    @Id
    @GeneratedValue
    private Long id = 0L;

    /**
     * The email field represents the email of the customer.
     * Note that the @NonNull annotation is a lombok annotation and not a JPA annotation
     * used to indicate that the field is required for the builder.
     */
    @NonNull
    private String email;

    /**
     * The version field is used by JPA for optimistic locking.
     * It is automatically updated by JPA every time the entity is updated in the database.
     */
    @Version
    Long version;
}
